class Autogenerated {
  bool? success;
  String? message;
  String? token;
  User? user;

  Autogenerated({this.success, this.message, this.token, this.user});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    token = json['token'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['message'] = this.message;
    data['token'] = this.token;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  int? id;
  String? name;
  String? noRumah;
  String? noTlp;
  String? alamat;
  String? email;
  Null? emailVerifiedAt;
  String? role;
  String? createdAt;
  String? updatedAt;

  User({
    this.id,
    this.name,
    this.noRumah,
    this.noTlp,
    this.alamat,
    this.email,
    this.emailVerifiedAt,
    this.role,
    this.createdAt,
    this.updatedAt,
  });

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    noRumah = json['no_rumah'];
    noTlp = json['no_tlp'];
    alamat = json['alamat'];
    email = json['email'];
    emailVerifiedAt = json['email_verified_at'];
    role = json['role'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['no_rumah'] = this.noRumah;
    data['no_tlp'] = this.noTlp;
    data['alamat'] = this.alamat;
    data['email'] = this.email;
    data['email_verified_at'] = this.emailVerifiedAt;
    data['role'] = this.role;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
